from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend" / "src"))

from kajovodagmar.main import create_app  # noqa: E402
from kajovodagmar.realtime.protocol import ClientEnvelope, ServerEnvelope  # noqa: E402


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(
            json.dumps(value, ensure_ascii=False) for value in schema["enum"]
        )
    variants = schema.get("anyOf") or schema.get("oneOf")
    if variants:
        return " | ".join(ts_type(item) for item in variants)
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(
            "null" if value == "null" else ts_type({"type": value}) for value in kind
        )
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            additional = schema.get("additionalProperties", {})
            return f"Record<string, {ts_type(additional) if isinstance(additional, dict) else 'unknown'}>"
        fields = []
        for name, value in properties.items():
            optional = "" if name in required else "?"
            fields.append(f"{json.dumps(name)}{optional}: {ts_type(value)}")
        return "{ " + "; ".join(fields) + " }"
    return "unknown"


def generate_types(openapi: dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = [
        "/* Generated by scripts/generate_contracts.py. Do not edit manually. */",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object" or "properties" in schema:
            lines.append(f"export type {name} = {ts_type(schema)};")
        else:
            lines.append(f"export type {name} = {ts_type(schema)};")
    lines.extend(
        [
            "",
            "export type ApiErrorEnvelope = { error: { code: string; message: string; details?: unknown; retryable?: boolean }; correlation_id?: string | null };",
            "",
        ]
    )
    return "\n".join(lines)


def outputs() -> dict[Path, bytes]:
    app = create_app()
    openapi = app.openapi()
    openapi["x-kajovodagmar-contract-version"] = "1.0"
    realtime = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://chat.hcasc.cz/schemas/realtime-v1.json",
        "protocol_version": "1.0",
        "$defs": {
            "ClientEnvelope": ClientEnvelope.model_json_schema(),
            "ServerEnvelope": ServerEnvelope.model_json_schema(),
        },
    }
    return {
        ROOT / "docs" / "api" / "openapi.v1.json": (
            json.dumps(openapi, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        ).encode(),
        ROOT / "docs" / "api" / "realtime.v1.schema.json": (
            json.dumps(realtime, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        ).encode(),
        ROOT / "web" / "src" / "api" / "generated" / "contracts.ts": generate_types(
            openapi
        ).encode(),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Vygeneruje nebo ověří REST a realtime kontrakty."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Nezapisovat; selhat, pokud jsou artefakty zastaralé.",
    )
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
            print(f"{path.relative_to(ROOT)} {hashlib.sha256(content).hexdigest()}")
    if stale:
        raise SystemExit("Zastaralé generované kontrakty: " + ", ".join(stale))


if __name__ == "__main__":
    main()
